### ISSUE TITLE
Is there a way to force opening as a tsv?

### ISSUE THREAD

**Issue by maximz** [timodonnell/pyopen#6]
There's a lot of tsv-formatted data online that has extension `.txt`. pyopen does not find a matching loader as-is, and with `--loader pandas_csv` it does not parse the `\t`'s. Is there a way to specify a loader like `pandas_tsv`?

**Comment by timodonnell** [comment]
Does specifying `--csv-delimiter "\t"` fix it?

**Comment by maximz** [comment]
yes! hadn't noticed that option. thanks.
